### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by clayball** [cryptolok/SteCoSteg#2]
Running a unstealth test using the provided image.jpg and text.txt works well against the PNG file the stealth process creates. However, in my case, I receive the following error when trying to unstealth and providing the key that was generated.

```
Traceback (most recent call last):
  File "./SteCoSteg.py", line 241, in <module>
    unstealth(decoy,file)
  File "./SteCoSteg.py", line 177, in unstealth
    coordinates.append((int(key[i*maxLength*2]+key[i*maxLength*2+1]+key[i*maxLength*2+2],16),int(key[i*maxLength*2+3]+key[i*maxLength*2+4]+key[i*maxLength*2+5],16)))
IndexError: string index out of range
```

I can get the unstealth to work if I provide the recovery JPG.

I'll try to spend some time with it soon.

Thank you

**Comment by clayball** [comment]
After many tests, I've narrowed this issue down to having something to do with the JPEG file I created.
The JPEG I created generates a key that looks like..

```
GENERATING KEY...

KEY : ecKlN6AxRdCaxorPTK+JyQ==
```

All of the tests that work generate keys similar to the following.

```
JhBeDEDXEYCnInC7KVBYCEBfJuDUKVCM
```

Clearly, something is different.

**Comment by cryptolok** [comment]
can you maybe send me the images in order I can debug? and the file that you tried to hide

**Comment by cryptolok** [comment]
i confirm the issue...
there is probably something wrong with the key generation/interpretation

**Comment by cryptolok** [comment]
more precisely, coordinates are not correctly restored, but the image is still modified accordingly
I'll patch it asap

**Comment by clayball** [comment]
Cool, thank you! And thank you for the awesome tool!

**Comment by cryptolok** [comment]
OK I got it
I simply didn't think about small images decoding, now it should be fine :)
Thanks for contribution
