### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by ghost** [cryptolok/SteCoSteg#4]
This error occured when starting `SteCoSteg.py` on Python 3.7.2 in Termux.
Based on this discussion [https://stackoverflow.com/questions/5685406/inconsistent-use-of-tabs-and-spaces-in-indentation](url) its probably because you use tabs instead of using space.

It would be great if you could add a new version of the script without using any tabs.

**Comment by cryptolok** [comment]
yep, totally forgot about it since fast-patching a bug
I replaced the spaces with tabs, this should resolve the situation regarding Python 3+ on any terminal
thx for notification
